<!DOCTYPE html>
<html lang="en">
<head>

    <?php $this->getChildHtml('head') ?>   
    <link rel="stylesheet" href="<?php echo Mage::getBaseUrl(). "skin/css/core/1column.css" ?>">

</head>
<body>
    <div class="container">
        <div class="header">
            <?php $this->getChildHtml('header') ?>
        </div>
        
        <div class="content">
            <?php $this->getChildHtml('content') ?>
        </div>
        




        
        <div class="footer">
            <?php $this->getChildHtml('footer') ?>
        </div>
    </div>
</body>
</html>
