<form action="" method="post">
        <table align="center" class="rounded-xl shadow-md">
            <tr>
                <th colspan=2>
                    <h1 class="m-3 text-xl">Forgot Password</h1>
                </th>
            </tr>

            <input class="input" type="hidden" name="custlogin[customer_id]">

            <tr>
                <td class="">
                    <label for="customer_email">Email Id</label>
                </td>
                <td>
                    <input class="input rounded-sm shadow-sm border-[#f2ebe5]" type="email" name="custlogin[customer_email]"  required>
                </td>
            </tr>
    
            
            <tr>
                <td class="">
                    <label for="password">Password</label>
                </td>
                <td>
                    <input class="input rounded-sm shadow-sm border-[#f2ebe5]" type="password" name="custlogin[password]"  required>
                </td>
            </tr>

            <tr>
                <td class="">
                    <label for="password">Confirm Password</label>
                </td>
                <td>
                    <input class="input rounded-sm shadow-sm border-[#f2ebe5]" type="password" name="custlogin[confirm_password]" required>
                </td>
            </tr>

            


            <tr>
                <th colspan=2>
                    <input class="bg-gray-600 p-1 rounded-md text-white m-3 cursor-pointer" type="submit" value="Change Password" />
                </th>
            </tr>
        </table>
    </form>