<?php $categoryData = $this->getCategory();?>
<?php $productData = $this->getProduct();?>

<div class="view m-5">
    <h1 class='text-2xl font-semibold text-center'><?php echo $categoryData->getCategoryName() ?></h1>

    <!-- <section>
        
    </section> -->

    <section class='m-5 ml-40 grid grid-cols-3 gap-10 '>
        <?php foreach ($productData->getData() as $product): ?>
            <a class='group hover:shadow-2xl transition duration-300 hover:scale-110 w-fit' href="<?php echo $this->getUrl('Catalog/Product/view')."?id=".$product->getProductId() ?>">
                <div class='w-60 h-80 bg-white rounded-md shadow-md border-gray-300 border-2 overflow-hidden'>
                    
                    <img class="w-60 h-60 transition duration-500 group-hover:scale-110" src="<?php echo ($this->getUrl('media/catalog/product/') . $product->getImageLink()); ?>"/>
                    
                    <div class='relative bg-white p-2 pt-4'>
                        <b class='text-sm truncate'><?php echo $product->getName() ?> </b><br>

                        <p class='text-sm mt-2'>₹<?php echo $product->getPrice() ?></p>
                    </div>                           
                            

                </div>
            </a>
        <?php endforeach; ?>
    </section>
    
</div>