<footer class="bg-[#10393b] m-3 rounded-lg shadow-md text-[#576861]">

        <section class="flex justify-between mx-16">

            <div class="m-5 p-5">
                <h5 class="text-gray-300 text-lg"><b>Navigate:</b></h5>
                <ul class="text-white ml-4">
                    <li><a href="./form">Home</a></li>
                    <li><a href="./list">Catalog</a></li>
                    <li><a href="#">Popular</a></li>
                    <li><a href="#">Search</a></li>
                </ul>
            </div>

            <div class="m-5 p-5">
                <h5 class="text-gray-300 text-lg"><b>Follow Us:</b></h5>
                <ul class="text-white ml-4">
                    <li><a href="#" >Facebook</a></li>
                    <li><a href="#" >Twitter(X)</a></li>
                    <li><a href="#">Instagram</a></li>
                    <li><a href="#">LinkedIn</a></li>
                </ul>
            </div>

            <div class="m-5 p-5">
                <h5 class="text-gray-300 text-lg"><b>Contact Us:</b></h5>
                <ul class="text-white ml-4">
                    <li>Savaj PG,</li>
                    <li>Nehrunagar Cross-Road,</li>
                    <li>Near Jain Derasar Temple</li>
                    <li>Ahmebadad</li>
                    <li>India - 380006</li>
                </ul>
            </div>

        </section>

        <div class="flex flex-col md:flex-row justify-between items-center text-gray-400 px-5">
            <div>
                <p>&copy; 2024 MardavParmar. All Rights Reserved.</p>
            </div>
            <div class="flex space-x-4 my-2 md:my-0">
                <a href="#">Privacy Policy</a>
                <a href="#">Coupons</a>
                <a href="#">Terms of Service</a>
            </div>
        </div>

</footer>
