<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Document</title>


<script src="<?php echo Mage::getBaseUrl(). "skin/js/tailwindcss.js" ?>"></script>
<script src="<?php echo Mage::getBaseUrl(). "skin/js/jquery-3.7.1.min.js" ?>"></script>
<!-- <script src="https://code.jquery.com/jquery-3.7.1.js" integrity="sha256-eKhayi8LEQwp4NKxN+CfCh+3qOVUtJn3QNZ0TciWLP4=" crossorigin="anonymous"></script> -->


<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />

<?php
$js = $this->getJs();
$css = $this->getCss(); ?>

<?php if (count($css)): ?>
        <?php foreach ($css as $_css): ?>
                <link rel="stylesheet" href="<?php echo $_css ?>">
        <?php endforeach ?>
<?php endif ?>

<?php if (count($js)): ?>
        <?php foreach ($js as $_js): ?>
                <script src="<?php echo $_js ?>"></script>
        <?php endforeach ?>
<?php endif ?>