<?php
$bannerCollection = Mage::getModel('banner/banner')->getCollection();
?>

<div align="center" class="view m-5">
    <h1 class='text-2xl'>Banner List</h1>
    <table class="w-full shadow-md rounded-lg mt-3">
        

        <?php foreach($bannerCollection->getData() as $bannerData):?>

            <tr class='flex mx-10 bg-white'>
                <td> 
                <img src="<?php echo ($this->getUrl('media/banner/') . $bannerData->getBannerImage()) ?>" class="bg-black w-96 h-48 border-2"/>
                
                
                </td>
                <td class='mt-20'>
                <b><?php echo $bannerData->getBannerTitle() ?> </b><br>
                <?php echo $bannerData->getBannerStatus() ?>
                </td>

                <td class='mt-20'> 
                <?php echo $bannerData->getShowOn() ?> <br>        
            </td>
                <td class='mt-16'><a href="
                <?php echo ($this->getUrl('Admin/Banner/form'). "?id=" . $bannerData->getBannerId()) ?>
                "><button  type='button' class="bg-blue-500 hover:bg-blue-900 text-white font-bold py-2 my-4 px-2 rounded">Edit</button></td>


                <td class='mt-16'><a href="
                <?php echo ($this->getUrl('Admin/Banner/delete'). "?id=" . $bannerData->getBannerId()) ?>
                "><button  type='button' class="bg-blue-500 hover:bg-blue-900 text-white font-bold py-2 my-4 px-2 rounded">Delete</button></td>
                


            </tr>
        <?php endforeach; ?>
    </table>
</div>